import type { Client } from "../types/clients.types";

export const clientsData: Client[] = [
    {
        img: '',
        name: 'Penny',
        surname: 'Tailor',
        recordingDate: '06/10/2020',
        recordingTime: '08:00 AM - 9:30 AM',
        status: 'Approved',
    },
    {
        img: '',
        name: 'Otis',
        surname: 'Wright',
        recordingDate: '06/10/2020',
        recordingTime: '10:00 AM - 11:00 AM',
        status: 'Need approve',
    },
    {
        img: '',
        name: 'Zayd',
        surname: 'Wilson',
        recordingDate: '06/10/2020',
        recordingTime: '11:30 AM - 13:00 AM',
        status: 'New',
    },
    {
        img: '',
        name: 'Penny',
        surname: 'Tailor',
        recordingDate: '06/10/2020',
        recordingTime: '08:00 AM - 9:30 AM',
        status: 'Refused',
    },
    {
        img: '',
        name: 'Penny',
        surname: 'Tailor',
        recordingDate: '06/10/2020',
        recordingTime: '08:00 AM - 9:30 AM',
        status: 'Approved',
    },
    {
        img: '',
        name: 'Zayd',
        surname: 'Wilson',
        recordingDate: '06/10/2020',
        recordingTime: '11:30 AM - 13:00 AM',
        status: 'New',
    },
    {
        img: '',
        name: 'Zayd',
        surname: 'Wilson',
        recordingDate: '06/10/2020',
        recordingTime: '11:30 AM - 13:00 AM',
        status: 'New',
    },
    {
        img: '',
        name: 'Penny',
        surname: 'Tailor',
        recordingDate: '06/10/2020',
        recordingTime: '08:00 AM - 9:30 AM',
        status: 'Refused',
    },
    {
        img: '',
        name: 'Penny',
        surname: 'Tailor',
        recordingDate: '06/10/2020',
        recordingTime: '08:00 AM - 9:30 AM',
        status: 'Refused',
    },
]